### PR TITLE
options.prepareDoc

### PR DESCRIPTION
**Pull request by gr2m**
```js
push('http://localhost:5984', 'path/to/doc.json', {
  prepareDoc: function (doc) {
    doc.foo = 'bar'
  }
}, function(err, response) {});
```

I'd like to use that to set custom passwords before bootstrapping _users docs.

### CODE REVIEW

**Comment by gr2m** [comment]
If that works for you, could we add it to https://github.com/eHealthAfrica/couchdb-bootstrap, too?

**Comment by jo** [comment]
I think we already have a mechanism to programatically change documents: CommonJS modules. Instead of pushing a JSON you can push arbitrary node modules, eg

doc.js
```js
module.exports = {
  name: 'My Name',
  password: process.env[PASSWORD]
}
``` 

and than 
```js
push('http://localhost:5984', 'path/to/doc.js, function(err, response) {});
```

**Comment by jo** [comment]
See http://docs.ehealthafrica.org/couchdb-best-practices/#commonjs-modules-%28aka-node-modules%29

**Comment by gr2m** [comment]
:v:

**Pull request closed without merging**
